#!/usr/bin/env bash
# Initialize counter
counter=1
# Loop while counter is less than or equal to 20
while [ $counter -le 20 ]; do
    # Display the current number
    echo $counter
    # Check for specific iterations
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    # Increment counter
    ((counter++))
done

